# A docker image specifically for machine learning work in Python.

# See dockerfiles/python3 for this image:
FROM python3

# Install common machine learning libraries:
RUN pip install pandas && pip install tensorflow

CMD ["python"]

